#!/usr/bin/env python
"""Run classical and diffusion-informed annealed SMC from a trained model.

Targets pi_{beta_target} (default beta=20) starting from pi_{beta_M} samples.
Initial particles come from either MCMC samples saved alongside the model, or
fresh samples generated by the diffusion model itself (fully amortised).

Usage:
    uv run python scripts/run_annealing.py <model_run_name>
    uv run python scripts/run_annealing.py <model_run_name> --init-source model
    uv run python scripts/run_annealing.py <model_run_name> --beta-target 20 --n-particles 2048
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch
import yaml

from amortised_annealing.diffusion import VPSchedule, MLPScore, ReverseSDE
from amortised_annealing.energies import DoubleWell, ManyWell, Ackley, Rastrigin
from amortised_annealing.sampling import DiffusionModelSampler
from amortised_annealing.smc import (
    ParticleCloud,
    SMCSampler,
    ULAProposal,
    DiffusionAnnealingProposal,
)

ROOT       = Path(__file__).parent.parent
MODEL_DIR  = ROOT / "data" / "models"
SAMPLE_DIR = ROOT / "data" / "samples"
OUTPUT_DIR = ROOT / "data" / "annealing"

ENERGY_MAP = {
    "double_well": DoubleWell,
    "many_well":   ManyWell,
    "ackley":      Ackley,
    "rastrigin":   Rastrigin,
}


def _resolve_device(s: str) -> torch.device:
    if s == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return torch.device(s)


def _load_model_run(run_name: str, device: torch.device):
    """Load a model run. Returns (reverse_sde, energy, dim, beta_m, sample_run_name)."""
    run_dir = MODEL_DIR / run_name
    with open(run_dir / "config.yaml") as f:
        cfg = yaml.safe_load(f)

    sample_run = cfg["samples"]["run_name"]
    sample_summary_path = SAMPLE_DIR / sample_run / "summary.json"
    with open(sample_summary_path) as f:
        sample_summary = json.load(f)

    energy_name = sample_summary["energy"]
    dim         = sample_summary["dim"]
    beta_m      = sample_summary["beta_m"]
    energy      = ENERGY_MAP[energy_name](dim=dim)

    model_cfg = cfg["model"]
    model = MLPScore(
        dim            = dim,
        hidden_dims    = tuple(model_cfg["hidden_dims"]),
        time_embed_dim = model_cfg.get("time_embed_dim", 64),
        activation     = model_cfg.get("activation", "silu"),
        predict_score  = model_cfg.get("predict_score", False),
    )
    state = torch.load(run_dir / "ema_model.pt", map_location=device, weights_only=True)
    model.load_state_dict(state)
    model.to(device).eval()

    sched_cfg = cfg["schedule"]
    schedule  = VPSchedule(
        beta_min=sched_cfg.get("beta_min", 0.1),
        beta_max=sched_cfg.get("beta_max", 20.0),
    )
    rsde = ReverseSDE(model, schedule)

    return rsde, energy, dim, beta_m, sample_run


def _get_initial_particles(
    init_source: str,
    rsde,
    sample_run: str,
    n_particles: int,
    n_diffusion_steps: int,
    device: torch.device,
) -> torch.Tensor:
    if init_source == "mcmc":
        pts = torch.load(SAMPLE_DIR / sample_run / "particles.pt", map_location=device, weights_only=True)
        # shape: [n_saved, n_snapshots, dim] — take last snapshot
        x = pts[:, -1, :]
        if x.shape[0] > n_particles:
            idx = torch.randperm(x.shape[0], device=device)[:n_particles]
            x = x[idx]
        elif x.shape[0] < n_particles:
            raise ValueError(
                f"Requested {n_particles} particles but only {x.shape[0]} MCMC samples saved. "
                "Lower --n-particles or regenerate samples."
            )
        return x.to(device)
    elif init_source == "model":
        sampler = DiffusionModelSampler(rsde, n_steps=n_diffusion_steps)
        return sampler.sample(n_particles, device, show_progress=True)
    else:
        raise ValueError(f"Unknown --init-source: {init_source!r}. Choose 'mcmc' or 'model'.")


def _energy_summary(x: torch.Tensor, energy_fn) -> dict:
    with torch.no_grad():
        e = energy_fn(x).float().cpu()
    return {
        "mean":   round(e.mean().item(), 4),
        "min":    round(e.min().item(), 4),
        "std":    round(e.std().item(), 4),
        "median": round(e.median().item(), 4),
    }


def _print_results(label: str, cloud, energy_fn, diag) -> None:
    summary = _energy_summary(cloud.x.cpu(), energy_fn)
    print(f"\n  [{label}]")
    print(f"    energy:  mean={summary['mean']:.4f}  min={summary['min']:.4f}  std={summary['std']:.4f}")
    print(f"    ESS/N:   final={cloud.ess_ratio():.3f}  resamples={diag.n_resamples}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("model_run", help="Model run name (subfolder of data/models/)")
    parser.add_argument("--init-source",        choices=["mcmc", "model"], default="mcmc",
                        help="Source of initial pi_{beta_M} particles (default: mcmc)")
    parser.add_argument("--beta-target",        type=float, default=20.0)
    parser.add_argument("--n-particles",        type=int,   default=2048)
    parser.add_argument("--n-smc-steps",        type=int,   default=50,
                        help="Steps in the beta ladder from beta_M to beta_target")
    parser.add_argument("--n-ula-steps",        type=int,   default=10,
                        help="ULA mutation steps per SMC step")
    parser.add_argument("--ula-step-size",      type=float, default=1e-3)
    parser.add_argument("--n-diffusion-steps",  type=int,   default=10,
                        help="Partial reverse SDE steps per SMC step (diffusion proposal)")
    parser.add_argument("--init-n-diffusion-steps", type=int, default=500,
                        help="Full reverse SDE steps when --init-source=model")
    parser.add_argument("--ess-threshold",      type=float, default=0.5)
    parser.add_argument("--no-progress",        action="store_true")
    parser.add_argument("--save",               action="store_true",
                        help="Save final particles and diagnostics to data/annealing/")
    args = parser.parse_args()

    # --- load ---
    run_dir = MODEL_DIR / args.model_run
    with open(run_dir / "config.yaml") as f:
        cfg = yaml.safe_load(f)
    device = _resolve_device(cfg["job"]["device"])
    torch.set_default_dtype(getattr(torch, cfg["job"]["dtype"]))

    rsde, energy, dim, beta_m, sample_run = _load_model_run(args.model_run, device)
    show_progress = not args.no_progress

    print(f"\nEnergy: {energy.__class__.__name__}  dim={dim}  beta_M={beta_m}  beta_H={args.beta_target}")
    print(f"Model:  {args.model_run}")
    print(f"Init:   {args.init_source}  N={args.n_particles}")

    # --- initial particles ---
    x0 = _get_initial_particles(
        args.init_source, rsde, sample_run,
        args.n_particles, args.init_n_diffusion_steps, device,
    )
    initial_cloud = ParticleCloud(x0, torch.zeros(args.n_particles, device=device))

    beta_ladder = torch.linspace(beta_m, args.beta_target, args.n_smc_steps + 1, device=device)

    # --- classical ULA SMC ---
    print(f"\n--- Classical SMC (ULA, {args.n_ula_steps} steps/β, step={args.ula_step_size}) ---")
    ula_proposal = ULAProposal(energy, step_size=args.ula_step_size, n_steps=args.n_ula_steps)
    ula_sampler  = SMCSampler(
        ula_proposal.mutation_kernel,
        ula_proposal.weight_update,
        energy,
        ess_threshold=args.ess_threshold,
    )
    ula_cloud, ula_diag = ula_sampler.run(initial_cloud, beta_ladder, show_progress=show_progress)

    # --- diffusion-informed SMC ---
    print(f"\n--- Diffusion SMC ({args.n_diffusion_steps} partial steps/β) ---")
    diff_proposal = DiffusionAnnealingProposal(
        rsde, energy, beta_train=beta_m,
        n_diffusion_steps=args.n_diffusion_steps,
    )
    diff_sampler = SMCSampler(
        diff_proposal.mutation_kernel,
        diff_proposal.weight_update,
        energy,
        ess_threshold=args.ess_threshold,
    )
    diff_cloud, diff_diag = diff_sampler.run(initial_cloud, beta_ladder, show_progress=show_progress)

    # --- results ---
    print(f"\n=== Results (target beta_H={args.beta_target}) ===")
    _print_results("ULA SMC",       ula_cloud,  energy, ula_diag)
    _print_results("Diffusion SMC", diff_cloud, energy, diff_diag)

    # --- save ---
    if args.save:
        tag = f"{args.model_run}_src-{args.init_source}_betaH{args.beta_target:.0f}"
        out_dir = OUTPUT_DIR / tag
        out_dir.mkdir(parents=True, exist_ok=True)

        results = {
            "model_run":         args.model_run,
            "init_source":       args.init_source,
            "beta_m":            beta_m,
            "beta_target":       args.beta_target,
            "n_particles":       args.n_particles,
            "n_smc_steps":       args.n_smc_steps,
            "ula": {
                "n_ula_steps":   args.n_ula_steps,
                "step_size":     args.ula_step_size,
                "n_resamples":   ula_diag.n_resamples,
                "final_ess":     ula_cloud.ess_ratio(),
                **_energy_summary(ula_cloud.x.cpu(), energy),
            },
            "diffusion": {
                "n_diffusion_steps": args.n_diffusion_steps,
                "n_resamples":   diff_diag.n_resamples,
                "final_ess":     diff_cloud.ess_ratio(),
                **_energy_summary(diff_cloud.x.cpu(), energy),
            },
        }
        with open(out_dir / "results.json", "w") as f:
            json.dump(results, f, indent=2)

        torch.save(ula_cloud.x.cpu(),  out_dir / "ula_particles.pt")
        torch.save(diff_cloud.x.cpu(), out_dir / "diff_particles.pt")
        print(f"\nSaved to {out_dir}")


if __name__ == "__main__":
    main()
